---
{{- if not .Values.backend.useExternal }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: fastapi-backend
        {{- include "helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: fastapi-backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/
              port: http
          readinessProbe:
            httpGet:
              path: /api/
              port: http
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- else }}
# fastapi-backend deployment skipped due external
{{- end -}}
