---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "registry"
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      {{- range $key, $value := $.Values.registry.spec }}
      {{ $key }}:
        {{ toYaml $value }}
      {{- end }}
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
          name: web
        volumeMounts:
        - name: registry-drive
          mountPath: /var/lib/registry
  volumeClaimTemplates:
  - metadata:
      name: registry-drive
    spec:
      storageClassName: {{ .Values.storage.className }}
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: registry-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: web
      protocol: TCP
  selector:
    app: registry
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: registry-svc
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.registry.hostname }}`)
      kind: Rule
      services:
        - namespace: {{ .Values.namespace }}
          name: registry-svc
          port: 80
