apiVersion: v1
kind: Service
metadata:
  name: fastapi-vue-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-vue-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8009
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: fastapi-vue-frontend
subsets:
  - addresses:
      - ip: {{ .Values.externalIp }}
    ports:
      - port: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: fastapi-vue-backend
subsets:
  - addresses:
      - ip: {{ .Values.externalIp }}
    ports:
      - port: 8009
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.hostname }}`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - namespace: {{ .Values.namespace }}
          name: fastapi-vue-backend
          port: 80
      middlewares:
        - name: fv-headers
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.hostname }}`)
      kind: Rule
      services:
        - namespace: {{ .Values.namespace }}
          name: fastapi-vue-frontend
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: fv-headers
  namespace: {{ .Values.namespace }}
spec:
  headers:
    customRequestHeaders:
      Host: localhost
