apiVersion: v1
kind: Service
metadata:
  name: fastapi-vue-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-vue-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ if .Values.backend.useExternal -}} 8009 {{- else -}} 80 {{- end }}
      protocol: TCP
  {{- if not .Values.backend.useExternal }}
  selector:
    app: fastapi-backend
  {{- end}}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: fastapi-vue-frontend
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
subsets:
  - addresses:
      - ip: {{ .Values.externalIp }}
    ports:
      - port: 8081
---
{{- if .Values.backend.useExternal }}
apiVersion: v1
kind: Endpoints
metadata:
  name: fastapi-vue-backend
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
subsets:
  - addresses:
      - ip: {{ .Values.externalIp }}
    ports:
      - port: 8009
{{- end}}
