apiVersion: v1
kind: Service
metadata:
  name: fastapi-vue-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-vue-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8009
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: fastapi-vue-frontend
subsets:
  - addresses:
      - ip: {{ .Values.externalIp }}
    ports:
      - port: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: fastapi-vue-backend
subsets:
  - addresses:
      - ip: {{ .Values.externalIp }}
    ports:
      - port: 8009
